/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;


import BLL.Perdoruesi;
import DAL.CrudFormException;
import DAL.PerdoruesiRepository;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arti
 */
public class MainFrom extends javax.swing.JFrame {

    ShowMenu sm;
    NewOrder no;
    ManageStaff ms;
    MngMenuItem mmi;
    ShowTotalSales sts;
    
    public MainFrom() throws CrudFormException {
        initComponents();
        setResizable(false);
        setPerdoruesi();
     
    }
    public MainFrom(int userRoli) throws CrudFormException{
    initComponents();
    setPerdoruesi();
    setLocationRelativeTo(null);
    setResizable(false);
    if(userRoli!=1){ 
     ManageE.setEnabled(false);
     ManageMI.setEnabled(false);
     ShowTS.setEnabled(false);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OrderM = new javax.swing.JButton();
        ShowM = new javax.swing.JButton();
        ManageE = new javax.swing.JButton();
        ManageMI = new javax.swing.JButton();
        ShowTS = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usr = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        log = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(new java.awt.Color(229,229,229));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 33, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderM.setBackground(new java.awt.Color(153, 163, 164));
        OrderM.setText("Order Managment");
        OrderM.setBorder(null);
        OrderM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderMActionPerformed(evt);
            }
        });
        jPanel1.add(OrderM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 163, 140, 55));

        ShowM.setBackground(new java.awt.Color(153, 163, 164));
        ShowM.setText("Show Menu");
        ShowM.setBorder(null);
        ShowM.setBorderPainted(false);
        ShowM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ShowM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowMActionPerformed(evt);
            }
        });
        jPanel1.add(ShowM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, 140, 55));

        ManageE.setBackground(new java.awt.Color(153, 163, 164));
        ManageE.setText("Manage Employees");
        ManageE.setBorder(null);
        ManageE.setBorderPainted(false);
        ManageE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEActionPerformed(evt);
            }
        });
        jPanel1.add(ManageE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 218, 140, 55));

        ManageMI.setBackground(new java.awt.Color(153, 163, 164));
        ManageMI.setText("Manage Menu Items");
        ManageMI.setBorder(null);
        ManageMI.setBorderPainted(false);
        ManageMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageMIActionPerformed(evt);
            }
        });
        jPanel1.add(ManageMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 273, 140, 55));

        ShowTS.setBackground(new java.awt.Color(153, 163, 164));
        ShowTS.setText("Show Total Sales");
        ShowTS.setBorder(null);
        ShowTS.setBorderPainted(false);
        ShowTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTSActionPerformed(evt);
            }
        });
        jPanel1.add(ShowTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 328, 140, 55));

        Logout.setBackground(new java.awt.Color(123, 125, 125));
        Logout.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 116, 42));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Perdoruesi eshte:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, 112, 26));

        usr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usr.setForeground(new java.awt.Color(240, 240, 240));
        usr.setText("Perdoruesi");
        jPanel1.add(usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 66, -1, -1));

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 33, 61), 2), "Restaurant Menagment System", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(20, 33, 61))); // NOI18N

        log.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(log)
                .addGap(350, 350, 350))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(log)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Desktop.setBackground(new java.awt.Color(229, 229, 229));
        Desktop.setInheritsPopupMenu(true);

        jLabel1.setBackground(new java.awt.Color(229, 229, 229));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/View/food-order1.png"))); // NOI18N

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        Desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Desktop)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowMActionPerformed
        
        try {
            sm = new ShowMenu();
            Desktop.add(sm);
            sm.show();
            log.setText("Show Menu");         
            
        } catch (Exception e) {
            Logger.getLogger(MainFrom.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }//GEN-LAST:event_ShowMActionPerformed

    private void OrderMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderMActionPerformed
        
        try {
            no = new NewOrder();
            Desktop.add(no);
            no.show();
            log.setText("New Order");
           
        } catch (Exception e) {
            Logger.getLogger(MainFrom.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_OrderMActionPerformed

    private void ManageEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEActionPerformed
        
        try {
            ms = new ManageStaff();
            Desktop.add(ms);
            ms.show();
            log.setText("Manage Staff");       
        } catch (Exception e) {
            Logger.getLogger(MainFrom.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ManageEActionPerformed

    private void ManageMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageMIActionPerformed
        
        try {
            mmi = new MngMenuItem();
            Desktop.add(mmi);
            mmi.show();
            log.setText("Manage Menu Items");
          
        } catch (Exception e) {
            Logger.getLogger(MainFrom.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ManageMIActionPerformed

    private void ShowTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTSActionPerformed
        
        
        try {
            sts = new ShowTotalSales();
            Desktop.add(sts);
            sts.show();
            log.setText("Show Total Sales");
            
        } catch (Exception e) {
            Logger.getLogger(MainFrom.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ShowTSActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
           Object[] obboi = {"YES","NO"};
           int o = JOptionPane.showOptionDialog(this, "Logout", "Logout",JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE,null,obboi,obboi[0]);
              if(o == 0){
               
               try {
                   new LoginForm().setVisible(true);
                   this.setVisible(false); 
                  
               } catch (Exception e) {
                 JOptionPane.showMessageDialog(this, e.getMessage());
               }
            
        }  

    }//GEN-LAST:event_LogoutActionPerformed

    public void setPerdoruesi() throws CrudFormException{       
    PerdoruesiRepository pr = new PerdoruesiRepository();
    LoginForm l = new LoginForm("d");
    Perdoruesi p = pr.loginByUsernameAndPassword(l.getUser(), l.getPass());
    usr.setText(p.getUsername());

    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrom().setVisible(true);
                } catch (CrudFormException ex) {
                    Logger.getLogger(MainFrom.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton Logout;
    private javax.swing.JButton ManageE;
    private javax.swing.JButton ManageMI;
    private javax.swing.JButton OrderM;
    private javax.swing.JButton ShowM;
    private javax.swing.JButton ShowTS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel log;
    private javax.swing.JLabel usr;
    // End of variables declaration//GEN-END:variables
}
