/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;


import BLL.Perdoruesi;
import BLL.Roli;
import DAL.CrudFormException;
import DAL.PerdoruesiRepository;
import DAL.RoliRepository;
import GUI.Model.PerdoruesiTableModel;
import GUI.Model.RoliComboBox;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Arti
 */
public class ManageStaff extends javax.swing.JInternalFrame {

    PerdoruesiTableModel ptm = new PerdoruesiTableModel();
    PerdoruesiRepository pr = new PerdoruesiRepository();
    RoliRepository rr = new RoliRepository();
    RoliComboBox rcmb = new RoliComboBox();
    
    
    
    
    
    public ManageStaff() {
        initComponents();
        loadTable();
        tableSIC();
        LoadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        AddStaff = new javax.swing.JButton();
        DeleteStaff = new javax.swing.JButton();
        ClearFields = new javax.swing.JButton();
        UsernameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RoliComboBox = new javax.swing.JComboBox();
        PasswordField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(725, 353));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        AddStaff.setText("Add/Save Staff");
        AddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStaffActionPerformed(evt);
            }
        });

        DeleteStaff.setText("Delete Staff");
        DeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStaffActionPerformed(evt);
            }
        });

        ClearFields.setText("ClearFields");
        ClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFieldsActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("Role");

        RoliComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(RoliComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClearFields)
                            .addComponent(DeleteStaff)
                            .addComponent(AddStaff))
                        .addGap(36, 36, 36)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AddStaff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteStaff)
                        .addGap(2, 2, 2)
                        .addComponent(ClearFields)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(2, 2, 2)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(2, 2, 2)
                                .addComponent(RoliComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void loadTable() {
        try{
        List <Perdoruesi> list = pr.FindALL();
        ptm.addList(list);
        table.setModel(ptm);
        ptm.fireTableDataChanged();
        }catch(CrudFormException e){
            Logger.getLogger(ManageStaff.class.getName()).log(Level.SEVERE,null,e);
        }
    }
     
     
     public void tableSIC(){
     final ListSelectionModel rowS = table.getSelectionModel();
     rowS.addListSelectionListener(new ListSelectionListener(){ 

         @Override
         public void valueChanged(ListSelectionEvent e) {
             if(e.getValueIsAdjusting()){
                 return;
             }
             
             ListSelectionModel rowS = (ListSelectionModel) e.getSource();
             int SelectedIndex = rowS.getAnchorSelectionIndex();
             if(SelectedIndex > -1){
                 Perdoruesi p = ptm.getUshqimet(SelectedIndex);
                 UsernameField.setText(p.getUsername());
                 PasswordField.setText(p.getPassword()); 
                 rcmb.setSelectedItem(p.getRoliID());
                 RoliComboBox.repaint();
                 
             }
         }
     
     });
    }
     
    public void LoadComboBox(){
    
        try {
            List<Roli> list = rr.FindALL();
            rcmb.add(list);
            RoliComboBox.setModel(rcmb);
            RoliComboBox.repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    
    
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void DeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStaffActionPerformed
       
        int row = table.getSelectedRow();
        if(row != -1){
           Object[] obboi = {"YES","NO"};
           int o = JOptionPane.showOptionDialog(this, "Delete staff memeber", "Delete",JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE,null,obboi,obboi[1]);
            
           if(o == 0){
               Perdoruesi p = ptm.getUshqimet(row);
               try {
                  pr.Delete(p); 
                  
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(this, e.getMessage());
               }
            clear();
            loadTable();
           }else{
            clear();
            loadTable();
            }
        
        
        }else{
           JOptionPane.showMessageDialog(this, "Select a staff memeber you want to remove");
        }
         
       
    }//GEN-LAST:event_DeleteStaffActionPerformed

    private void AddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStaffActionPerformed
       try{ 
            int row = table.getSelectedRow();
            if(row == -1){
            Perdoruesi p = new Perdoruesi();
            p.setUsername(UsernameField.getText());
            p.setPassword(PasswordField.getText());
            p.setRoliID((Roli)rcmb.getSelectedItem());
            pr.Create(p);
           }else{
             Perdoruesi p = ptm.getUshqimet(row);
             p.setUsername(UsernameField.getText());
             p.setPassword(PasswordField.getText());
             p.setRoliID((Roli)rcmb.getSelectedItem());
             pr.Edit(p);
            }
            clear();
            loadTable();
        } catch (CrudFormException e){
            JOptionPane.showMessageDialog(this,"Please fill all the fields.");
        }
    }//GEN-LAST:event_AddStaffActionPerformed

    private void ClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFieldsActionPerformed
        clear();
    }//GEN-LAST:event_ClearFieldsActionPerformed

    
    
    
    public void clear(){
    table.clearSelection();
    UsernameField.setText("");
    PasswordField.setText("");
    RoliComboBox.setSelectedIndex(-1);
    RoliComboBox.repaint();
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStaff;
    private javax.swing.JButton ClearFields;
    private javax.swing.JButton DeleteStaff;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JComboBox RoliComboBox;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
