/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.LlojiUshqimit;
import BLL.Ushqimet;
import DAL.CrudFormException;
import DAL.LlojiUshqimitRepository;
import DAL.UshqimiRepository;
import GUI.Model.LlojiUshqimitComboBox;
import GUI.Model.UshqimiTableModel;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Arti
 */
public class MngMenuItem extends javax.swing.JInternalFrame {

    UshqimiTableModel utm = new UshqimiTableModel();
    UshqimiRepository ur = new UshqimiRepository();
    LlojiUshqimitRepository llur = new LlojiUshqimitRepository();
    LlojiUshqimitComboBox llucmb = new LlojiUshqimitComboBox();
    
    public MngMenuItem() {
        initComponents();
        loadTable();
        tableSIC();
        LoadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        AddNew = new javax.swing.JButton();
        DeleteItem = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        ItemNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ItemTypeBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ItemPriceField = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(725, 353));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        AddNew.setText("Add/Save menu Item");
        AddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewActionPerformed(evt);
            }
        });

        DeleteItem.setText("Delete menu item");
        DeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemActionPerformed(evt);
            }
        });

        Clear.setText("Clear Fields");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu item name");

        jLabel2.setText("Menu Item price");

        ItemTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Menu item type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(ItemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(ItemPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(ItemTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AddNew)
                                .addGap(35, 35, 35)
                                .addComponent(DeleteItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                                .addComponent(Clear)
                                .addGap(51, 51, 51)))))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNew)
                    .addComponent(DeleteItem)
                    .addComponent(Clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    public void loadTable() {
        try{
        List <Ushqimet> list = ur.FindALL();
        utm.addList(list);
        table.setModel(utm);
        utm.fireTableDataChanged();
        }catch(CrudFormException e){
            Logger.getLogger(MngMenuItem.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    
     public void tableSIC(){
     final ListSelectionModel rowS = table.getSelectionModel();
     rowS.addListSelectionListener(new ListSelectionListener(){ 

         @Override
         public void valueChanged(ListSelectionEvent e) {
             if(e.getValueIsAdjusting()){
                 return;
             }
             
             ListSelectionModel rowS = (ListSelectionModel) e.getSource();
             int SelectedIndex = rowS.getAnchorSelectionIndex();
             if(SelectedIndex > -1){
                 Ushqimet u = utm.getUshqimet(SelectedIndex);
                 ItemNameField.setText(u.getEmriUshqimit().toString());
                 ItemPriceField.setText(String.valueOf(u.getCmimi())); 
                 llucmb.setSelectedItem(u.getLlojiushqimitId());
                 ItemTypeBox.repaint();
                 
             }
         }
     
     });
    }
     
    public void LoadComboBox(){
    
        try {
            List<LlojiUshqimit> list = llur.FindALL();
            llucmb.add(list);
            ItemTypeBox.setModel(llucmb);
            ItemTypeBox.repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    
    
    }
    
    
    
    private void DeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemActionPerformed
        
        int row = table.getSelectedRow();
        if(row != -1){
           Object[] obboi = {"YES","NO"};
           int o = JOptionPane.showOptionDialog(this, "Delete Item from the menu", "Delete",JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE,null,obboi,obboi[1]);
            
           if(o == 0){
               Ushqimet u = utm.getUshqimet(row);
               try {
                  ur.Delete(u); 
                  
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(this, e.getMessage());
               }
            clear();
            loadTable();
           }else{
            clear();
            loadTable();
            }
        
        
        }else{
           JOptionPane.showMessageDialog(this, "Select the item you want to delete");
        }
         
       
        
    }//GEN-LAST:event_DeleteItemActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        clear();
    }//GEN-LAST:event_ClearActionPerformed

    private void AddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewActionPerformed
         try{ 
            int row = table.getSelectedRow();
            if(row == -1){
            Ushqimet u = new Ushqimet();
            BigDecimal b = new BigDecimal(ItemPriceField.getText());
            u.setEmriUshqimit(ItemNameField.getText());
            u.setCmimi(b);
            u.setLlojiushqimitId((LlojiUshqimit)llucmb.getSelectedItem());
            ur.Create(u);
           }else{
             BigDecimal b =new BigDecimal(ItemPriceField.getText());
             Ushqimet u = utm.getUshqimet(row);
             u.setEmriUshqimit(ItemNameField.getText());
             u.setCmimi(b);
             u.setLlojiushqimitId((LlojiUshqimit)llucmb.getSelectedItem());
             ur.Edit(u);
            }
            clear();
            loadTable();
        } catch (CrudFormException e){
            JOptionPane.showMessageDialog(this,"Please fill all the fields.");
        } catch (Exception e){
           JOptionPane.showMessageDialog(this,"Please Write the Price"); 
        }
    }//GEN-LAST:event_AddNewActionPerformed

    public void clear(){
    table.clearSelection();
    ItemNameField.setText("");
    ItemPriceField.setText("");
    ItemTypeBox.setSelectedIndex(-1);
    ItemTypeBox.repaint();
    
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNew;
    private javax.swing.JButton Clear;
    private javax.swing.JButton DeleteItem;
    private javax.swing.JTextField ItemNameField;
    private javax.swing.JTextField ItemPriceField;
    private javax.swing.JComboBox ItemTypeBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
