/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.OrderMenu;
import BLL.Perdoruesi;
import BLL.Ushqimet;
import DAL.CrudFormException;
import DAL.OrderRepository;
import DAL.PerdoruesiRepository;
import DAL.UshqimiRepository;
import GUI.Model.OrderTableModel;
import GUI.Model.UshqimiTableModel;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Arti
 */
public class NewOrder extends javax.swing.JInternalFrame {

     UshqimiTableModel utm = new UshqimiTableModel();
     UshqimiRepository ur = new UshqimiRepository();
     OrderRepository or = new OrderRepository();
     OrderTableModel otm = new OrderTableModel();
     
    public NewOrder() throws CrudFormException {
        initComponents();
        loadTable1();
        loadTable2();
        totalP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        MainB = new javax.swing.JButton();
        Alcohol = new javax.swing.JButton();
        Drink = new javax.swing.JButton();
        Dessert = new javax.swing.JButton();
        All = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        TodayO = new javax.swing.JButton();
        AllO = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(725, 353));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        MainB.setText("Main");
        MainB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainBActionPerformed(evt);
            }
        });

        Alcohol.setText("Alcohol");
        Alcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlcoholActionPerformed(evt);
            }
        });

        Drink.setText("Drink");
        Drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinkActionPerformed(evt);
            }
        });

        Dessert.setText("Dessert");
        Dessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertActionPerformed(evt);
            }
        });

        All.setText("All");
        All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(All)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Drink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Alcohol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dessert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(All)
                    .addComponent(MainB)
                    .addComponent(Drink)
                    .addComponent(Alcohol)
                    .addComponent(Dessert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table2);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.setPreferredSize(new java.awt.Dimension(51, 23));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("Total:");

        Total.setText("0.0$");

        TodayO.setText("Today's Orders");
        TodayO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodayOActionPerformed(evt);
            }
        });

        AllO.setText("All Orders");
        AllO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TodayO)
                        .addGap(34, 34, 34)
                        .addComponent(AllO, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Total)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TodayO)
                    .addComponent(AllO))
                .addGap(94, 94, 94))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainBActionPerformed
         try{
        List <Ushqimet> list = ur.FindMain();
        utm.addList(list);
        table1.setModel(utm);
        utm.fireTableDataChanged();
        }catch(CrudFormException e){
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_MainBActionPerformed

    private void AlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlcoholActionPerformed
        try{
        List <Ushqimet> list = ur.FindAlcohol();
        utm.addList(list);
        table1.setModel(utm);
        utm.fireTableDataChanged();
        }catch(CrudFormException e){
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_AlcoholActionPerformed

    private void DrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinkActionPerformed
        try{
        List <Ushqimet> list = ur.FindDrinks();
        utm.addList(list);
        table1.setModel(utm);
        utm.fireTableDataChanged();
        }catch(CrudFormException e){
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_DrinkActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
         int row = table2.getSelectedRow();
        if(row != -1){
           Object[] obboi = {"Yes","NO"};
           int i = JOptionPane.showOptionDialog(this, "Delete Order from the order table", "Delete",JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE,null,obboi,obboi[1]);
            
           if(i == 0){
               
               OrderMenu o = otm.getOrderMenu(row);
               try {
                  or.Delete(o); 
                   totalP();
                  
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(this, e.getMessage());
               }
            
            loadTable2();
           }else{
            
            loadTable2();
            }
        
        
        }else{
           JOptionPane.showMessageDialog(this, "Select the order you want to delete");
        }
         
    }//GEN-LAST:event_DeleteActionPerformed

    private void AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllActionPerformed
         try{
        List <Ushqimet> list = ur.FindALL();
        utm.addList(list);
        table1.setModel(utm);
        utm.fireTableDataChanged();
        }catch(CrudFormException e){
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_AllActionPerformed

    private void DessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertActionPerformed
        try{
        List <Ushqimet> list = ur.FindDessert();
        utm.addList(list);
        table1.setModel(utm);
        utm.fireTableDataChanged();
        }catch(CrudFormException e){
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_DessertActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
           int row = table1.getSelectedRow(); 
        if(row == -1){ 
           JOptionPane.showMessageDialog(this, "Select the item you want to order");
        }else {
         try { 
            Date date = new Date();
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
            String strDate = dateFormat.format(date);
            OrderMenu o = new OrderMenu();
            PerdoruesiRepository pr = new PerdoruesiRepository();       
            Ushqimet u = utm.getUshqimet(row);
            LoginForm l = new LoginForm("d");
            Perdoruesi p = pr.loginByUsernameAndPassword(l.getUser(), l.getPass()); 
            o.setEmriUshqimitId(u);
            o.setPerdoruesiId(p);
            o.setDataEPorosis(strDate);
            or.Create(o);
            totalP();
            BigDecimal t = u.getCmimi();
            loadTable2();
         } catch (CrudFormException ex) {
             Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        
        
        
        }
        
    }//GEN-LAST:event_AddActionPerformed

    private void TodayOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodayOActionPerformed
        try{ 
        List <OrderMenu> list = or.filterOrderByToday();
        otm.addList(list);
        table2.setModel(otm);
        otm.fireTableDataChanged();
        todayTotalP();
        }catch(CrudFormException e){
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_TodayOActionPerformed

    private void AllOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllOActionPerformed
         try {
             totalP();
             loadTable2();
         } catch (CrudFormException ex) {
             Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_AllOActionPerformed
 
    public void loadTable1(){
        try{
        List <Ushqimet> list = ur.FindALL();
        utm.addList(list);
        table1.setModel(utm);
        utm.fireTableDataChanged();
        }catch(CrudFormException e){
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    public void loadTable2(){
        try{
        List <OrderMenu> list = or.FindALL();
        otm.addList(list);
        table2.setModel(otm);
        otm.fireTableDataChanged();
        }catch(CrudFormException e){
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    
    
    public void totalP() throws CrudFormException {
       BigDecimal t = or.totalPrice();
       Total.setText(String.valueOf(t)+ "$");  
    }
    public void todayTotalP() throws CrudFormException {
       BigDecimal t = or.todayTotalPrice();
       Total.setText(String.valueOf(t)+ "$");  
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Alcohol;
    private javax.swing.JButton All;
    private javax.swing.JButton AllO;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Dessert;
    private javax.swing.JButton Drink;
    private javax.swing.JButton MainB;
    private javax.swing.JButton TodayO;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
